apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dotnetapp
  labels:
    app: worker
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: docker.iranrepo.ir/arpjoker/worker_dotnet
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
