apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: result
  labels:
    app: result
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: docker.iranrepo.ir/arpjoker/nodejs
        ports:
        - containerPort: 80
        - containerPort: 5858

---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  selector:
    app: result
  ports:
    - name: fir
      protocol: TCP
      port: 80
      targetPort: 80
    - name : sec
      protocol: TCP
      port: 5858
      targetPort: 5858
