apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote
  labels:
    app: vote
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote 
    spec:
      containers:
      - name: vote
        image: arpjoker/python_front
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
      ## test if redis service is up (has problems)
      #initContainers:
      #- name: redistest
      #  image: docker.iranrepo.ir/busybox:1.28
      #  command:
      #  - nslookup
      #  - redis
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - name: access
      protocol: TCP
      port: 80
      nodePort: 30001

